### ISSUE TITLE
Quoridor 구성과 규칙

### ISSUE THREAD

**Issue by junnie082** [SeoulTechTCPGame/block-it#7]
# TODO

## 공통
- [x] 상대방과 나에게 남은 플랭크의 개수가 각각 표시
- [x] 보드판 배치
- [ ] 상대방의 프로필 사진은 좌측 상단에, 내 프로필 사진은 우측 하단에 표현됨
- [ ]  턴 표시(내 턴이 아닐 때는 회색 띠가 프로필 사진 주변에 생김)
- [ ] 프로필 사진 주위에 랭크에 맞는 색띠가 표현됨
- [ ] 우측 상단에 설정버튼이 있다.
- [x] 설정 버튼 클릭 시 설정 팝업창이 생김
  - [x] 음악 변경
  - [x] 효과음 변경
  - [x] 진동 변경
  - [x] 옵션 변경 시 전체 옵션이 동일하게 변경이 됨

## play

- [x] 플레이어를 이동시키거나 플랭크를 두는 행동을 나타내는 버튼 두 개
- [x] 플레이어 버튼에서 [put] 버튼을 누르면 해당 방향으로 이동하는 것이 확정됨
- [x] 플랭크 버튼에서 플랭크를 둘 위치를 누른 후에 더블 클릭하면 ([put] 버튼을 누르면) 그곳에 플랭크가 두어지는 것이 확정됨
- [x] 게임 시작 시, 상대 플레이어는 맨 위에 중앙에 배치, 내 플레이어는 맨 아래 중앙에 배치
- [ ] 화면의 [give up] 버튼을 누르면 게임을 그만 둘지를 물을 팝업창이 뜸
- [ ] [exit] 버튼을 누르면 게임이 취소되고 홈화면으로 돌아가며, [cancel] 버튼을 누르면 게임으로 돌아옴
- [ ] 내 턴에서는 '플레이어' 버튼이 처음에 눌려진 상태로 시작됨
- [x] 쿼리도는 본인의 플레이어를 상대 진영으로 먼저 보내면 이김

## result
 게임이 끝나면, 해당 씬에서 아래와 같은 변경이 생김
- [ ] +, - 된 포인트 텍스트
- [ ] [give up] 버튼이 사라지고 재대결 신청 버튼과 나가기 버튼, 복기하기 버튼이 생김
- [ ] 복기하기 버튼 클릭 시 플레이의 맨처음으로 넘어가진다.
- [ ] 플레이어 버튼과 플랭크 버튼이 "<",">"으로 대체
- [ ] 화살표 버튼을 클릭 시 보드판을 게임의 과정을 순차적으로 보여줌

## 구성

- 메인 보드판 (9x9)
- 플레이어 두 개 (원래의 쿼리도 게임에서는 4인 플레이 가능하지만, 우리가 만들 프로그램은 2인 플레이만 가능합니다.)
- 플랭크 (각 플레이어마다 10개씩)

## 규칙

[쿼리도의 규칙(위키백과)](https://namu.wiki/w/쿼리도)

- 쿼리도는 본인의 플레이어를 상대 진영으로 먼저 보내면 이기는 게임입니다. 여기서 상대 진영이란, 본인 플레이어의 시작점을 기준으로 상대의 시작점인 마지막 줄을 의미합니다. 
- 플레이어는 턴마다 플레이어를 이동시키거나 나무 판자를 놓는 동작 중에 한 가지를 선택할 수 있습니다. 
- 플레이어는 상,하,좌,우 중 하나의 이동 방향을 선택할 수 있습니다. 
- 플랭크는 보드판의 칸을 두 개 차지합니다. 한 칸만 차지하거나 보드판의 경계를 넘어 판자를 둘 수 없습니다. 
- 플레이어끼리 만나면, 플레이어는 상대 플레이어를 뛰어 넘을 수 있습니다. 

### 주의할 점

[피그마](https://www.figma.com/file/t7zt3aqK1ccUGSmFl3mR0V/Quoridor_cases?node-id=0%3A1&t=xFhSqj9ZZDTohd5T-1)

1. 상대를 뛰어 넘어 이동하려고 하는 방향에 이미 나무 판자가 존재할 때는 각 상황마다 플레이어가 이동할 수 있는 곳이 정해져 있습니다. 

![Image](https://user-images.githubusercontent.com/88719152/233144378-b341f1ee-ec1b-4810-9c5d-8268055ba7f6.png)
![Image](https://user-images.githubusercontent.com/88719152/233144376-2bf2b2ae-210c-433d-b544-2e52c47f1c71.png)
![Image](https://user-images.githubusercontent.com/88719152/233144375-40b0a5b2-b7e9-4e61-ac03-c5d93e50f194.png)
![Image](https://user-images.githubusercontent.com/88719152/233144380-58c561b1-6686-4e57-b5f2-b47a915afabc.png)
![Image](https://user-images.githubusercontent.com/88719152/233144377-4845b1b3-cb6d-479c-84ca-e2e1b46154a4.png)
![Image](https://user-images.githubusercontent.com/88719152/233144379-974002da-1596-4604-8324-2a09eb65ff83.png)

2. 각 플레이어가 상대 진영에 도달할 수 있는 길이 최소 한 개 이상 있어야 합니다. 즉, 나무 판자로 플레이어의 모든 진로를 막을 수는 없습니다.

![Image](https://user-images.githubusercontent.com/88719152/233145624-d9764997-4222-4e1b-a927-23c24808512e.png)

**Comment by seong0929** [comment]
세세히 이슈를 분리하여 관리함
